---
name: Compile Doom SDL

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - master
      - main

jobs:
  windows_build:
    # runs-on: ubuntu-latest
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          # pacboy: >-
          #   cmake:p
          #   cc:p
          #   glib2:p
          #   libxml2:p
          #   python-setuptools:p

      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest

      - name: "Build Doom with SDL"
        working-directory: doomgeneric
        run: |
          make -j2 -f Makefile.sdl

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          path:
          name: doomgeneric.exe
          compression-level: 0
          if-no-files-found: error
